### ISSUE TITLE
Subtle dependency not truly optional

### ISSUE THREAD

**Issue by squili** [mikelodder7/vsss-rs#2]
In `src/utils.rs`, `subtle` is unconditionally used, but in `Cargo.toml`, `subtle` is marked as optional. This causes builds to fail. I would try to fix it myself, but all the tests fail as well, which cannot be a good sign.

**Comment by mikelodder7** [comment]
Good catch. I'll post another update to fix that/

**Comment by mikelodder7** [comment]
Fixed
