### ISSUE TITLE
Support for >255 shamir parties

### ISSUE THREAD

**Issue by delbonis** [mikelodder7/vsss-rs#5]
Hi, I noticed this bit in `shamir.rs`:

```rs
        // Generate the shares of (x, y) coordinates
        // x coordinates are incremental from [1, N+1). 0 is reserved for the secret
        let mut shares = Vec::with_capacity(self.n);
        let mut x = F::one();
        for i in 0..self.n {
            let y = polynomial.evaluate(x, self.t);
            let mut t = Vec::with_capacity(1 + y.to_repr().as_ref().len());
            t.push((i + 1) as u8);
            t.extend_from_slice(y.to_repr().as_ref());

            shares.push(Share(t));

            x += F::one();
        }
        (shares, polynomial)
```

And this comment in `share.rs`:

```
/// The first byte is the X-coordinate or identifier
/// The remaining bytes are the Y-coordinate
```

I'm not sure if it's documented explicitly, but it seems to point to only supporting secret sharing with up to 255 parties.  I was wondering how much might need to be changed to support a greater number of parties (potentially on the order of a few thousand).  I'm assuming just changing the structure of the `Share` type and changing a few other constants, right?

**Comment by mikelodder7** [comment]
Yes it would be easy. However in practice I’ve found more than a few dozen and it starts to get ridiculous. I’m interested to hear your use case for that high

**Comment by delbonis** [comment]
We're trying to do cooperative signing of cryptocurrency transactions (similar to what Ren is doing with a secret shared key), although it turns out we don't actually need that many parties since we're structuring it differently than I expected.
